<a href="https://colab.research.google.com/github/Leonavichus/python/blob/main/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Лабораторная работа №2***

**NUMPY**

**1. Задать вектора а и b, найти из сумму.**

In [2]:
import numpy as np
a = np.array([1,2,3])
b = np.array([10,0.2,3])
a+b

array([11. ,  2.2,  6. ])

**2. Массив b преобразовать в массив комплексных чисел.**

In [4]:
import numpy as np
b = np.array([[1.5,2,3], [4,5,6]], dtype=np.complex)
b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

**3. Создать числовую последовательность от 10 до 30 с шагом 5.**

In [5]:
import numpy as np
np.arange(10,30,5)

array([10, 15, 20, 25])

**4. Создать массив из 15 элементов. Развернуть его (первый становится последним).**

In [6]:
import numpy as np
Z = np.arange(15)
Z = Z[::-1]
Z

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**5. Создать массив 10x10 со случайными значениями, найти минимум и максимум.**

In [7]:
import numpy as np
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
Zmin, Zmax

(0.0018432071773007985, 0.9979344155060037)

**6. Создать случайный вектор размера 30 и найти среднее значение всех элементов.**

In [8]:
import numpy as np
Z = np.random.random(30)
m = Z.mean()
m

0.47455335228041

***PANDAS***

**7. Создать объект Series, вывести на экран.**

In [9]:
import pandas as pd
my_series = pd.Series([5,6,7,8,9,10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [20]:
import pandas as pd
df = pd.DataFrame({
  'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
  'population': [17.04, 143.5, 9.5, 45.5],
  'square': [2724902, 17125191, 207600 ,603628]

})
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [21]:
import pandas as pd
df = pd.DataFrame({
  'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
  'population': [17.04, 143.5, 9.5, 45.5],
  'square': [2724902, 17125191, 207600 ,603628]

})
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

***Самостоятельная работа***

In [24]:
import pandas as pd
df = pd.DataFrame({
  'ФИО': ['Леонавичус Д.К', 'Бондаренко И.В', 'Белоусов М.Д', 'Рудзей Н.П', 'Погорелов А.А'],
  'Номер зачетки': [123324231, 123321342, 123324324, 123322341, 123323423],
  'Курс': [4, 4, 4 ,4, 4]
})
df

ФИО  Номер зачетки  Курс
0  Леонавичус Д.К      123324231     4
1  Бондаренко И.В      123321342     4
2    Белоусов М.Д      123324324     4
3      Рудзей Н.П      123322341     4
4   Погорелов А.А      123323423     4